### ISSUE TITLE
LibGmsh2Specfem_convert_Gmsh_to_Specfem2D_official.py , it can not work well in par with Gmsh_4.1.5

### ISSUE THREAD

**Issue by brioglade** [geodynamics/specfem2d#1034]
~/specfem2d/EXAMPLES/Gmsh_example_Stacey_MPI/MESH,in this file,if I mesh SqrCirc.geo in Gmsh_4.1.5,it turn out that -
ufo@doughnut:~/specfem2d/EXAMPLES/Gmsh_example_Stacey_MPI/MESH$ sudo ./LibGmsh2Specfem_convert_Gmsh_to_Specfem2D_official.py SqrCirc1.msh -t F -l A -b A -r A
[sudo] password for ufo:
#################### STARTING PROCESSING ####################
File :  SqrCirc1.msh
------------------------------------------------------------
{'Right': 'Abso', 'Top': 'Free', 'Left': 'Abso', 'Bottom': 'Abso'}
Number of physical Names :  6
PML :  False
(1, 1, 'Top')
(1, 2, 'Left')
(1, 3, 'Bottom')
(1, 4, 'Right')
(2, 5, 'M1')
(2, 6, 'M2')
------------------------------------------------------------
Absorbing boundaries :  [2, 3, 4]
Free boundaries :  [1]
------------------------------------------------------------
Right boundaries :  4
Left boundaries :  2
Top boundaries :  1
Bottom boundaries :  3
------------------------------------------------------------
Med :  [0. 0. 0. 0. 0. 1. 2.]
Number of nodes:  27
Number of elements:  7
Traceback (most recent call last):
  File "./LibGmsh2Specfem_convert_Gmsh_to_Specfem2D_official.py", line 445, in <module>
    OuvreGmsh('',Fic, Bords)
  File "./LibGmsh2Specfem_convert_Gmsh_to_Specfem2D_official.py", line 200, in OuvreGmsh
    (string.split(lignes[Pos])[5:])]
ValueError: cannot copy sequence with size 0 to array axis with dimension 2

Comparing with the mesh from Gmsh_2.0.8 (hitting format in the SqrCirc.msh),they are different too.
Is LibGmsh2Specfem_convert_Gmsh_to_Specfem2D_official.py  outdated ?

**Comment by danielpeter** [comment]
thanks for pointing out!

yes, the script LibGmsh2Specfem_convert_Gmsh_to_Specfem2D_official.py requires the (legacy) MSH format 2. please consider saving your mesh with the added option -format msh22 for now.

for example, run:
gmsh SqrCirc.geo -2 -order 2 -format msh22 -o SqrCirc.msh

this will work with Gmsh version 4.x and will produce the right mesh format for the specfem script to work.
