### ISSUE TITLE
ERRORS IN SPECFEM2D 

### ISSUE THREAD

**Issue by loycbt** [geodynamics/specfem2d#1056]
Dear developer,
I got a problem when I ran specfem2d. The error is presented below.  
Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:
#0  0x7F18F1A92E08
#1  0x7F18F1A91F90
#2  0x7F18F11C34AF
#3  0x7F18F17986F0
#4  0x48C5B4 in get_simulation_domains_ at get_simulation_domains.f90:62
#5  0x518005 in read_mesh_databases_ at read_mesh_databases.F90:323
#6  0x40235D in specfem2d at specfem2D.F90:363
#7  0x7F18F11AE82F
./run_this_example.sh: line 64:  6987 Floating point exception(core dumped) ./xspecfem2D

**Comment by nivanrs** [comment]
have you check courant stability?

**Comment by loycbt** [comment]
> have you check courant stability?
Dear nivanrs
Thank you. I have checked out the time step and solved this problem. But another problem is the computing time  is too long. About 20000 element need more than 13 hours.  I don't know whether it is reasonable or not. Does the quality of the mesh have a great influence on the computation time ?
Regards, 
loycbt

**Comment by loycbt** [comment]
> have you check courant stability?


have you check courant stability? Dear nivanrs Thank you. I have checked out the time step and solved this problem. But  another problem is the computing time  is too long. About 20000 element  need more than 13 hours.  I don't know whether it is reasonable or not.  Does the quality of the mesh have a great influence on the computation  time ? 
Regards, loycbt
--

**Comment by loycbt** [comment]
> have you check courant stability?

Dear nivanrs,
Thank you for your help. I have checked out the time step and solved this problem. But  another problem is the computing time  is too long. About 20000 element  need more than 13 hours.  I don't know whether it is reasonable or not.  Does the quality of the mesh have a great influence on the computation  time ? 

Regards, 
loycbt
--

**Comment by danielpeter** [comment]
i don't think it is related to the stability criterion. the last readable line you point out:

`
#4 0x48C5B4 in get_simulation_domains_ at get_simulation_domains.f90:62
`

indicates a problem with your mesh elements and the materials you assign to them. please check that all elements have a valid material id assigned, thus becomes consistent with your material definitions in the Par_file.

**Comment by loycbt** [comment]
> i don't think it is related to the stability criterion. the last readable line you point out:
> 
> `#4 0x48C5B4 in get_simulation_domains_ at get_simulation_domains.f90:62`
> 
> indicates a problem with your mesh elements and the materials you assign to them. please check that all elements have a valid material id assigned, thus becomes consistent with your material definitions in the Par_file.

Thank you.

**Comment by PAULGOYES** [comment]
If I have xmax = 400 zmax = 200 and .. a single material:

**Comment by loycbt** [comment]
> If I have xmax = 400 zmax = 200 and .. a single material:
> 1 1 2200.d0 3200.d0 1847.5d0 0 0 9999 9999 0 0 0 0 0 0
> How Can I calculate NX, NZ and DT ? In order to find the stability criterion

You can have a test and check the stability condition in the terminal, and then set DT based on the output.

**Comment by PAULGOYES** [comment]
> > If I have xmax = 400 zmax = 200 and .. a single material:
> > 1 1 2200.d0 3200.d0 1847.5d0 0 0 9999 9999 0 0 0 0 0 0
> > How Can I calculate NX, NZ and DT ? In order to find the stability criterion
> 
> You can have a test and check the stability condition in the terminal, and then set DT based on the output.

you are right, but for a simple model 400-by-200 meters, I got this:
 **Maximum suggested time step                 =    5.1801949393802927E-005**
but, this sampling time is too small, I will need at least 50000 samples to reach 1 second.

Can you please help me check the data in this link: I will appreciate it so much! 
https://www.dropbox.com/sh/1af157yen67bcqf/AADVBBC28IdLZTRLtzuLwng9a?dl=0
